exclude: |
  (?x)^(
    mkdocs.yml
  )$

default_language_version:
  python: python3.10

default_stages: [ pre-commit, pre-push, commit, push ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: trailing-whitespace

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: 0.3.4
    hooks:
      - id: auto-walrus

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.4.10'  # Must match requirements-dev.txt
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1  # Must match requirements-dev.txt
    hooks:
      - id: mypy
        additional_dependencies:
          - 'pandera~=0.17.2'  # Must match requirements.txt
          - 'pydantic~=2.3.0'  # Must match requirements.txt

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [ --no-update ]

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: '1.8.0'
    hooks:
      - id: poetry-export
        args: [ --without-hashes, -f, requirements.txt, -o, requirements.txt ]
      - id: poetry-export
        args: [ --without-hashes, --only, "dev,test,docs", -f, requirements.txt, -o, requirements-dev.txt ]
