exclude: |
  (?x)^(
    mkdocs.yml
  )$

default_language_version:
  python: python3.10

default_stages: [ pre-commit, pre-push ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: trailing-whitespace

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: 0.3.4
    hooks:
      - id: auto-walrus

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.12.8'  # Should match poetry.lock
    hooks:
      - id: ruff-check
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1  # Should match poetry.lock
    hooks:
      - id: mypy
        additional_dependencies:
          - 'pandera[mypy]~=0.25.0'  # Should match poetry.lock
          - 'pydantic~=2.11.7'  # Should match poetry.lock

  - repo: https://github.com/python-poetry/poetry
    rev: '2.1.4'
    hooks:
      - id: poetry-check
      - id: poetry-lock
