coverage:
  status:
    project:
      default:
        target: 90%    # the required coverage value. Should match fail_under in pyproject.toml's [tool.coverage.report]
        threshold: 1%  # the leniency in hitting the target

codecov:
  require_ci_to_pass: false
