site_name: My Project
site_url: https://eshwen.github.io/ds-python-boilerplate/
repo_url: https://github.com/eshwen/ds-python-boilerplate
repo_name: eshwen/ds-python-boilerplate

nav:
  - Home:
      - Homepage: index.md
      - Helpful Articles: helpful-articles.md
      - General Python Tips: general-python-tips.md
      - See Also: see-also.md
  - Getting Started:
      - Installation: getting-started/getting-started.md
      - Poetry: getting-started/poetry.md
      - Conda: getting-started/conda.md
      - Development Container: getting-started/dev-container.md
  - Tooling:
      - Quality: tooling/quality.md
      - Testing: tooling/testing.md
      - Documentation: tooling/documentation.md
      - Pipelines: tooling/pipelines.md
  - Code Reference: reference/

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
          import:
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/pandas-docs/stable/objects.inv
            - https://docs.sqlalchemy.org/en/14/objects.inv
  - search:
      lang: en
  - autorefs
  - termynal
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mike:
      alias_type: symlink
      canonical_version: latest

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light blue
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/code_select.css

markdown_extensions:
  - toc:
      permalink: ⚓︎
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eshwen
      name: eshwen on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eshwen-bhal-phd-714557195/
      name: Eshwen Bhal on LinkedIn
  version:
    provider: mike