site_name: My Project
repo_url: https://github.com/eshwen/ds-python-boilerplate
repo_name: eshwen/ds-python-boilerplate

nav:
  - Home: index.md
  - Getting Started: getting-started.md

plugins:
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
          import:
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/pandas-docs/stable/objects.inv
            - https://docs.sqlalchemy.org/en/14/objects.inv
  - search:
      lang: en
  - autorefs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light blue
      accent: orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: ⚓︎
  - attr_list
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eshwen
      name: eshwen on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eshwen-bhal-phd-714557195/
      name: Eshwen Bhal on LinkedIn
