name: API documentation
on:
  push:
    branches:
      - main

jobs:

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/builder

      - name: Build docs
        run: |
          git fetch
          mkdocs gh-deploy
