name: API documentation
on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: docs-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    permissions:
      contents: 'write'
      actions: 'write'

    uses: eshwen/adrenaline/.github/workflows/api-docs-build.yml@v0.1.1
    with:
      python-version: 3.10
      changelog: 'CHANGELOG.md'
