name: API documentation
on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: docs-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/builder

      - name: Build docs
        run: |
          git fetch --unshallow
          git-changelog -p github -o CHANGELOG.md
          mkdocs gh-deploy
