name: API documentation

on:
  release:
    types:
      - published

concurrency:
  group: docs-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    permissions:
      contents: 'write'
      actions: 'write'

    uses: eshwen/adrenaline/.github/workflows/api-docs-build.yml@v0.2.2
    with:
      python-version: '3.10'
      changelog: 'CHANGELOG.md'
