name: "Python Docstring Validity Checks"

on:
  push:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # --match-dir argument ignores files in tests/ as they're not needed in documentation
      # --match argument ignores __init__.py files
      # D301 complains when a docstring has a backslash and isn't a raw string
      - name: Python Docstring Checker
        run: |
          pip install pydocstyle==6.1.1
          python -m pydocstyle --count --convention google --add-ignore D301 --match-dir '(?!(tests)).*' --match '(?!__init__).*\.py'
        if: ${{ always() }}
