name: Check quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: eshwen/adrenaline/.github/workflows/python-quality-check.yml@v0.2.3
    with:
      python-version: '3.10'
      path: 'my_project/'
