name: Check quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: eshwen/adrenaline/.github/workflows/python-quality-check.yml@4e6998cfa85863fb6aec1d9fe77330af3bc91172
    with:
      python-version: 3.10
      path: 'my_project/'
