name: Check quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: eshwen/adrenaline/workflows/python-quality-check.yml@v0.2.0
    with:
      python-version: 3.10
      path: 'my_project/'
