name: Check quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    uses: eshwen/adrenaline/.github/workflows/python-quality-check.yml@v0.6.0
    with:
      python-version: '3.10'
      path: 'my_project/'
