name: Check quality

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check quality
        uses: eshwen/adrenaline/.github/workflows/python-quality-check.yml@v0.1.1
        with:
          python-version: 3.10
          path: 'my_project/'
