name: Test Python Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v5

      - name: Test
        uses: eshwen/adrenaline/test-python@v0.6.0
        with:
          python-version: ${{ matrix.python-version }}
          pkg-name: 'my_project/'
          args: '--cov-report xml'

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Test docs
        if: always()
        run: |
          poetry run mkdocs build --strict
        shell: bash
